on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Gatsby Publish
      uses: enriikke/gatsby-gh-pages-action@v2.2.1
      with:
        deploy-branch: gh-pages

          
